#!/bin/sh
# Regenerates src/width_table.inc from the real Vim (vim -Nu NONE -es, in a scratch directory, never on a repo file). Needs vim on the PATH;
# changes nothing but that file. Building and running notvim does not need Vim, only this script does.
# Wide: strdisplaywidth(c) == 2 (from U+00A0 up). Combining: a character that adds no column after a base ("e" . c is one column wide).
# Surrogates and what Vim shows as <xxxx> are not in either list.
# Usage: tests/gen-width-table.sh        (from anywhere; then review the diff and run make test)
set -eu
here=$(cd "$(dirname "$0")" && pwd)
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
cat > "$work/gen.vim" <<'VIM'
set encoding=utf-8
function! Ranges(name, cond)
  let lines = ['static const range_t ' . a:name . '[] = {']
  let lo = -1
  let prev = -1
  for n in range(0xa0, 0x10ffff)
    if n >= 0xd800 && n <= 0xdfff
      let hit = 0
    else
      let hit = eval(substitute(a:cond, 'N', n, 'g'))
    endif
    if hit && lo < 0
      let lo = n
    elseif !hit && lo >= 0
      call add(lines, printf("\t{ 0x%x, 0x%x },", lo, n - 1))
      let lo = -1
    endif
  endfor
  if lo >= 0
    call add(lines, printf("\t{ 0x%x, 0x10ffff },", lo))
  endif
  call add(lines, '};')
  return lines
endfunction
let out = []
call extend(out, Ranges('wide_ranges', 'strdisplaywidth(nr2char(N)) == 2'))
call add(out, '')
call extend(out, Ranges('combining_ranges', 'N >= 0x300 && strdisplaywidth("e" . nr2char(N)) == 1'))
call writefile(out, $WORK . '/ranges.inc')
qa!
VIM
WORK="$work" vim -Nu NONE -es -S "$work/gen.vim"
{
	echo "/* Generated by tests/gen-width-table.sh from $(vim --version | head -1 | sed 's/ *(.*//'). Do not edit by hand. */"
	cat "$work/ranges.inc"
} > "$here/../src/width_table.inc"
